site_name: Solana.py
theme:
  name: material
  icon:
    logo: material/snake
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.snippets
  - meta
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/michaelhly/solana-py
repo_name: michaelhly/solana-py
site_url: https://michaelhly.github.io/solana-py/
site_author: Kevin Heavey & Michael Huang
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            filters:
              - "!^_" # exlude all members starting with _
              - "^__init__$" # but always include __init__ modules and methods
            show_root_heading: true
            show_bases: false
  - search
nav:
  - index.md
  - RPC API:
      - rpc/api.md
      - rpc/async_api.md
      - rpc/websocket.md
      - rpc/commitment.md
      - rpc/types.md
      - rpc/providers.md
  - Core API:
      - core/api.md
  - Solana Program Library (SPL):
      - spl/intro.md
      - Token:
          - spl/token/client.md
          - spl/token/async_client.md
          - spl/token/constants.md
          - spl/token/instructions.md
          - spl/token/core.md
      - Memo Program:
          - spl/memo/intro.md
          - spl/memo/constants.md
          - spl/memo/instructions.md
  - Cookbook:
      - cookbook/index.md
      - Development Guides:
          - cookbook/development-guides/connecting-to-solana.md
          - cookbook/development-guides/getting-test-sol.md
          - cookbook/development-guides/subscribing-to-events.md
          - cookbook/development-guides/create-account.md
      - Account Management:
          - cookbook/account-management/calculate-account-creation-cost.md
          - cookbook/account-management/create-pda-account.md
          - cookbook/account-management/get-account-balance.md
      - Token Operations:
          - cookbook/token-operations/create-token.md
          - cookbook/token-operations/get-token-mint.md
          - cookbook/token-operations/create-token-account.md
          - cookbook/token-operations/get-token-account.md
          - cookbook/token-operations/get-token-balance.md
          - cookbook/token-operations/mint-tokens.md
          - cookbook/token-operations/burn-tokens.md
          - cookbook/token-operations/transfer-tokens.md
          - cookbook/token-operations/close-token-account.md
          - cookbook/token-operations/get-all-token-accounts-by-owner.md
          - cookbook/token-operations/set-authority.md
          - cookbook/token-operations/delegate-token-account.md
          - cookbook/token-operations/revoke-delegate.md
          - cookbook/token-operations/wrapped-sol.md
      - Transaction Operations:
          - cookbook/transaction-operations/send-sol.md
          - cookbook/transaction-operations/send-tokens.md
          - cookbook/transaction-operations/calculate-transaction-cost.md
          - cookbook/transaction-operations/add-memo-to-transaction.md
          - cookbook/transaction-operations/add-priority-fees.md
          - cookbook/transaction-operations/optimize-compute-requested.md
          - cookbook/transaction-operations/offline-transactions.md
      - Wallet Management:
          - cookbook/wallet-management/create-keypair.md
          - cookbook/wallet-management/restore-keypair.md
          - cookbook/wallet-management/verify-keypair.md
          - cookbook/wallet-management/validate-public-key.md
          - cookbook/wallet-management/sign-verify-message.md
extra_css:
  - css/mkdocstrings.css
